version: "3.3"

services:
  faceid:
    container_name: faceid
    # build: .
    image: cmac01/app-faceid:dev01
    restart: always
    
    ports:
      - 5000:5000
    devices:
      - /dev/video0:/dev/video0   
     
    volumes:       
      - ./deepface:/app/deepface
      - ./api/app.py:/app/api/app.py
      - ./api/routes.py:/app/api/routes.py
      - ./api/service.py:/app/api/service.py
      - ./api/find.py:/app/api/find.py
      - ./setup.py:/app/setup.py
      - ./representations:/app/representations
      - ./employee:/app/employee   
    # networks:
    #   - catracaApp
    # command: ["python", "./api/find.py"]
    command: ["gunicorn", "--workers=1", "--timeout=3600", "--bind=0.0.0.0:5000", "app:create_app()"]
    tty: true
#networks:
#  catracaApp:
#    external: true
