version: "3.3"

services:
  faceid:
    container_name: faceid
    build: .
#    image: sanjeetpal/deepface
    restart: always
    ports:
       - 5000:5000
    volumes:
       - ./autorizados:/autorizados
       - ./deepface:/app/deepface
    devices:
       - /dev/video0:/dev/video0       
#       - ./api:/app
#      - 3571:3571
#      - 3570:3570
#    networks:
#      - catracaApp

#networks:
#  catracaApp:
#    external: true
