version: "3.3"

services:
  faceid:
    container_name: faceid
    # build: .
    image: cmac01/app-faceid:dev01
    restart: always
    ports:
       - 5000:5000
       
#    volumes:
#       - ./api:/app
#      - 3571:3571
#      - 3570:3570
#    networks:
#      - catracaApp

#networks:
#  catracaApp:
#    external: true
