version: "3"

services:
  faceid:
    container_name: faceid
    env_file:
      - .env
    image: cmac01/app-faceid:dev01
    restart: always
    
    ports:
      - 7000:7000
    # devices:
    #   - /dev/video0:/dev/video0   
     
    volumes:       
      - ${VOLUME_PATH}deepface:/opt/app/deepface      
      - ${VOLUME_PATH}api/routes.py:/opt/app/api/routes.py
      - ${VOLUME_PATH}api/service.py:/opt/app/api/service.py      
      - ${VOLUME_PATH}api/main.py:/opt/app/api/main.py      
      - ${VOLUME_PATH}setup.py:/opt/app/setup.py
      - ${VOLUME_PATH}representations:/opt/app/representations
      - ${VOLUME_PATH}employee:/opt/app/employee   
    # networks:
    #   - catracaApp
    # mudar o contexto para a pasta api
    # working_dir: /opt/api    
    #command: ["flask", "run", "--host=localhost", "--port=5000"]
    # command: ["gunicorn", "--workers=1", "--timeout=3600", "--bind=0.0.0.0:5000", "app:create_app()"]
    # command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "7000","--reload"]
    # tty: true
#networks:
#  catracaApp:
#    external: true
